services:
  - type: web
    name: investment-site
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && python manage.py shell < create_admin.py && gunicorn investment.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        value: "securepassword"
