# Generated by Django 5.1.7 on 2025-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deposit_transaction_id_alter_deposit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='network',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BSC', 'Binance Smart Chain'), ('USDT', 'USDT')], max_length=50),
        ),
    ]
